---
- name: Provision Memory API
  hosts: all

  pre_tasks:
    - name: Load secrets
      include_tasks: ../tasks/load-secrets.yml

  roles:
    - nodejs
    - postgresql
    - nginx
    - memory-api

  tasks:
    - name: Run pending migrations
      include_tasks: ../tasks/run-migrations.yml
